version: 2

project_name: coredns-externaldns

before:
  hooks:
    - make deps

builds:
  - main: ./cmd/coredns-externaldns
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.appName=CoreDNS-ExternalDNS
      - -X main.appVersion={{.Version}}

kos:
  - repositories:
      - ghcr.io/ionos-cloud/coredns-externaldns
    tags:
      - latest
      - "{{ .Tag }}"
    platforms:
      - linux/arm64
      - linux/amd64
    base_image: alpine
    bare: true
    sbom: none

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}.{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
