# Plugin Configuration for CoreDNS External-DNS
external-dns:
  # Kubernetes configuration
  namespace: ""   # Watch specific namespace, empty for all namespaces
  
  # Cache settings
  ttl: 300        # Default TTL for DNS records in seconds
  
  # Debugging
  debug: false
  
# Note: This plugin uses in-cluster service account authentication
# Ensure proper RBAC permissions are configured for the service account
